In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('../datasets/fridge_price_predictor.csv')
data.head()

,Brand,Model,Capacity,Energy Rating,Type,Features,Color,Material,Warranty Period,Country of Manufacture,Price,Random Numeric Feature 1,Random Text Feature 2,Irrelevant Category Feature 3
0,Panasonic,Model0,369.0,A++,NaN,NaN,NaN,Stainless Steel,5.0,Germany,1231.0,3984.0,Text0,Category3
1,GE,Model1,619.0,A,Side-by-Side,Smart Connectivity,White,Glass,8.0,Germany,267.0,3155.0,Text1,Category3
2,GE,Model2,309.0,A,Single Door,Ice Dispenser,Black,Stainless Steel,7.0,India,477.0,2218.0,Text2,Category2
3,LG,Model3,662.0,B,Side-by-Side,Ice Dispenser,Gray,Plastic,8.0,India,NaN,4734.0,Text3,Category2
4,Bosch,Model4,533.0,B,Double Door,Water Dispenser,Gray,Plastic,NaN,India,993.0,4259.0,Text4,Category1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Brand                          20000 non-null  object
 1   Model                          19000 non-null  object
 2   Capacity                       19012 non-null  float64
 3   Energy Rating                  19000 non-null  object
 4   Type                           19000 non-null  object
 5   Features                       14226 non-null  object
 6   Color                          19000 non-null  object
 7   Material                       19000 non-null  object
 8   Warranty Period                19000 non-null  float64
 9   Country of Manufacture         19000 non-null  object
 10  Price                          19000 non-null  float64
 11  Random Numeric Feature 1       19000 non-null  float64
 12  Random Text Feature 2          19000 non-null  object
 13  Irrelevant Category Feature 3  19000 non-null  object
dtypes: float64(4), object(10)
memory usage: 2.1+ MB

In [4]:
data.shape

(20000, 14)

In [5]:
data.drop(['Random Numeric Feature 1', 'Random Text Feature 2', 'Irrelevant Category Feature 3', 'Model'], axis=1, inplace = True)

In [6]:
data.head()

,Brand,Capacity,Energy Rating,Type,Features,Color,Material,Warranty Period,Country of Manufacture,Price
0,Panasonic,369.0,A++,NaN,NaN,NaN,Stainless Steel,5.0,Germany,1231.0
1,GE,619.0,A,Side-by-Side,Smart Connectivity,White,Glass,8.0,Germany,267.0
2,GE,309.0,A,Single Door,Ice Dispenser,Black,Stainless Steel,7.0,India,477.0
3,LG,662.0,B,Side-by-Side,Ice Dispenser,Gray,Plastic,8.0,India,NaN
4,Bosch,533.0,B,Double Door,Water Dispenser,Gray,Plastic,NaN,India,993.0

In [7]:
data.duplicated().sum()

0

In [8]:
data.isnull().sum()

Brand                        0
Capacity                   988
Energy Rating             1000
Type                      1000
Features                  5774
Color                     1000
Material                  1000
Warranty Period           1000
Country of Manufacture    1000
Price                     1000
dtype: int64

In [9]:
data['Warranty Period'].fillna(0.0, inplace=True)

C:\Users\RAYANEH INS\AppData\Local\Temp\ipykernel_19444\4026635784.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Warranty Period'].fillna(0.0, inplace=True)

In [10]:
data.head()

,Brand,Capacity,Energy Rating,Type,Features,Color,Material,Warranty Period,Country of Manufacture,Price
0,Panasonic,369.0,A++,NaN,NaN,NaN,Stainless Steel,5.0,Germany,1231.0
1,GE,619.0,A,Side-by-Side,Smart Connectivity,White,Glass,8.0,Germany,267.0
2,GE,309.0,A,Single Door,Ice Dispenser,Black,Stainless Steel,7.0,India,477.0
3,LG,662.0,B,Side-by-Side,Ice Dispenser,Gray,Plastic,8.0,India,NaN
4,Bosch,533.0,B,Double Door,Water Dispenser,Gray,Plastic,0.0,India,993.0

In [11]:
data.isnull().sum()

Brand                        0
Capacity                   988
Energy Rating             1000
Type                      1000
Features                  5774
Color                     1000
Material                  1000
Warranty Period              0
Country of Manufacture    1000
Price                     1000
dtype: int64

In [12]:
data.dropna(inplace= True)

In [13]:
data.isnull().sum()

Brand                     0
Capacity                  0
Energy Rating             0
Type                      0
Features                  0
Color                     0
Material                  0
Warranty Period           0
Country of Manufacture    0
Price                     0
dtype: int64

In [14]:
input = data.drop('Price', axis=1)

In [15]:
input.head()

,Brand,Capacity,Energy Rating,Type,Features,Color,Material,Warranty Period,Country of Manufacture
1,GE,619.0,A,Side-by-Side,Smart Connectivity,White,Glass,8.0,Germany
2,GE,309.0,A,Single Door,Ice Dispenser,Black,Stainless Steel,7.0,India
4,Bosch,533.0,B,Double Door,Water Dispenser,Gray,Plastic,0.0,India
5,GE,371.0,A++,Single Door,Smart Connectivity,Silver,Glass,4.0,Germany
6,GE,288.0,B,Double Door,Smart Connectivity,White,Glass,6.0,USA

In [16]:
target = data['Price']
target

1         267.0
2         477.0
4         993.0
5         462.0
6        1906.0
          ...
19988     432.0
19989     881.0
19991     399.0
19996     870.0
19999    1573.0
Name: Price, Length: 9913, dtype: float64

In [30]:
input['Brand'].unique()

array(['GE', 'Bosch', 'LG', 'Haier', 'Panasonic', 'Siemens', 'Frigidaire',
       'Electrolux', 'Whirlpool', 'Samsung', 'Br@ndX'], dtype=object)

In [17]:
brand = LabelEncoder()
input['brand'] = brand.fit_transform(input['Brand'])

In [19]:
EnergyRating = LabelEncoder()
input['EnergyRating'] = EnergyRating.fit_transform(input['Energy Rating'])

In [29]:
input['Type'].unique()

array(['Side-by-Side', 'Single Door', 'Double Door'], dtype=object)

In [21]:
type = LabelEncoder()
input['type'] = type.fit_transform(input['Type'])

In [28]:
input['Features'].unique()

array(['Smart Connectivity', 'Ice Dispenser', 'Water Dispenser'],
      dtype=object)

In [25]:
features = LabelEncoder()
input['features'] = features.fit_transform(input['Features'])

In [27]:
data.Color.unique()

array(['White', 'Black', 'Gray', 'Silver'], dtype=object)

In [31]:
color = LabelEncoder()
input['color'] = color.fit_transform(input['Color'])

In [33]:
input['Material'].unique()

array(['Glass', 'Stainless Steel', 'Plastic'], dtype=object)

In [34]:
material = LabelEncoder()
input['material'] = material.fit_transform(input['Material'])

In [36]:
input['Country of Manufacture'].unique()

array(['Germany', 'India', 'USA', 'China'], dtype=object)

In [37]:
country = LabelEncoder()
input['country'] = material.fit_transform(input['Country of Manufacture'])

In [38]:
input.head()

,Brand,Capacity,Energy Rating,Type,Features,Color,Material,Warranty Period,Country of Manufacture,brand,EnergyRating,type,features,color,material,country
1,GE,619.0,A,Side-by-Side,Smart Connectivity,White,Glass,8.0,Germany,4,0,1,1,3,0,1
2,GE,309.0,A,Single Door,Ice Dispenser,Black,Stainless Steel,7.0,India,4,0,2,0,0,2,2
4,Bosch,533.0,B,Double Door,Water Dispenser,Gray,Plastic,0.0,India,0,3,0,2,1,1,2
5,GE,371.0,A++,Single Door,Smart Connectivity,Silver,Glass,4.0,Germany,4,2,2,1,2,0,1
6,GE,288.0,B,Double Door,Smart Connectivity,White,Glass,6.0,USA,4,3,0,1,3,0,3

In [41]:
input.drop(['Brand', 'Energy Rating', 'Type', 'Features', 'Color', 'Material', 'Country of Manufacture'], axis= 1, inplace= True)

In [42]:
input.head()

,Capacity,Warranty Period,brand,EnergyRating,type,features,color,material,country
1,619.0,8.0,4,0,1,1,3,0,1
2,309.0,7.0,4,0,2,0,0,2,2
4,533.0,0.0,0,3,0,2,1,1,2
5,371.0,4.0,4,2,2,1,2,0,1
6,288.0,6.0,4,3,0,1,3,0,3

In [59]:
scaler = StandardScaler()
scaler.fit(input)
x_scaled = scaler.transform(input)

In [60]:
x_scaled

array([[ 0.83550044,  1.17692453, -0.45297144, ...,  1.32014858,
        -1.21048612, -0.42382003],
       [-0.66564546,  0.81248343, -0.45297144, ..., -1.36098907,
         1.25449928,  0.46085631],
       [ 0.41905351, -1.73860425, -1.76659857, ..., -0.46727652,
         0.02200658,  0.46085631],
       ...,
       [-1.52275135, -1.00972205,  0.20384212, ..., -0.46727652,
        -1.21048612,  1.34553265],
       [-0.16687763, -1.37416315,  1.18906246, ..., -1.36098907,
         1.25449928, -1.30849637],
       [ 0.92750616,  0.44804233, -0.45297144, ..., -1.36098907,
         1.25449928,  1.34553265]])

In [71]:
target = x_scaled

In [72]:
x_train , x_test, y_train, y_test= train_test_split(input, target, test_size= 0.2)

In [73]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [74]:
y_pred = model.predict(x_test)

In [75]:
model.predict([[533.0,	0.0,	0,	3,	0,	2,	1,	1,	2]])

c:\Users\RAYANEH INS\miniconda3\envs\my_env\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[ 0.41905351, -1.73860425, -1.76659857,  1.34503155, -1.23487516,
         1.20741071, -0.46727652,  0.02200658,  0.46085631]])

In [76]:
model.score(x_test, y_test)*100

100.0

In [77]:
mean_squared_error(y_test, y_pred)

5.167984138228925e-27