In [14]:
import numpy as np
import pandas as pd
from sklearn import linear_model

import warnings
warnings.filterwarnings('ignore')

In [15]:
df = pd.read_csv('datasets/hiring.csv')
df

  experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [16]:
df.experience = df.experience.fillna('zero').astype('str')
df

  experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [17]:
df.test_score = df.test_score.fillna(df.test_score.median())
df

  experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [18]:
df.isnull().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

In [19]:
pip install word2number

Requirement already satisfied: word2number in c:\users\asus\anaconda3\lib\site-packages (1.1)
Note: you may need to restart the kernel to use updated packages.

In [20]:
pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

In [21]:
from word2number import w2n

In [22]:
df.experience= df.experience.apply(w2n.word_to_num)
df

   experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [23]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score', 'interview_score']], df.salary)

LinearRegression()

In [24]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [25]:
reg.intercept_

17737.263464337688

In [26]:
reg.predict([[2, 9, 6]])

array([53205.96797671])

In [27]:
reg.predict([[12, 10, 10]])

array([92002.18340611])

# Save


# pickel

In [28]:
import pickle

In [29]:
with open('pickle_LinMultiVar_Prac', 'wb') as f:
    pickle.dump(reg, f)

In [30]:
with open('pickle_LinMultiVar_Prac', 'rb') as f:
    mp = pickle.load(f)

In [31]:
mp.predict([[12, 10, 10]])

array([92002.18340611])


# joblib

In [32]:
import joblib

In [33]:
joblib.dump( reg,'joblib_LinMultiVar_Prac')

['joblib_LinMultiVar_Prac']

In [34]:
mj = joblib.load('joblib_LinMultiVar_Prac')

In [35]:
mj.predict([[10, 10, 2]])

array([68734.35225619])