In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('datasets/carprices.csv')
df

   Car Model  Mileage  Sell Price($)  Age(yrs)
0     BMW X5    69000          18000         6
1     BMW X5    35000          34000         3
2     BMW X5    57000          26100         5
3     BMW X5    22500          40000         2
4     BMW X5    46000          31500         4
5    Audi A5    59000          29400         5
6    Audi A5    52000          32000         5
7    Audi A5    72000          19300         6
8    Audi A5    91000          12000         8
9   Mercedez    67000          22000         6
10  Mercedez    83000          20000         7
11  Mercedez    79000          21000         7
12  Mercedez    59000          33000         5

In [3]:
df= df.rename(columns={'Car Model': 'car_model','Sell Price($)':'SellPrice','Age(yrs)':'Age'})
df

   car_model  Mileage  SellPrice  Age
0     BMW X5    69000      18000    6
1     BMW X5    35000      34000    3
2     BMW X5    57000      26100    5
3     BMW X5    22500      40000    2
4     BMW X5    46000      31500    4
5    Audi A5    59000      29400    5
6    Audi A5    52000      32000    5
7    Audi A5    72000      19300    6
8    Audi A5    91000      12000    8
9   Mercedez    67000      22000    6
10  Mercedez    83000      20000    7
11  Mercedez    79000      21000    7
12  Mercedez    59000      33000    5

In [4]:
dummies = pd.get_dummies(df.car_model)

In [5]:
merged = pd.concat([df, dummies], axis='columns')
merged

   car_model  Mileage  SellPrice  Age  Audi A5  BMW X5  Mercedez
0     BMW X5    69000      18000    6        0       1         0
1     BMW X5    35000      34000    3        0       1         0
2     BMW X5    57000      26100    5        0       1         0
3     BMW X5    22500      40000    2        0       1         0
4     BMW X5    46000      31500    4        0       1         0
5    Audi A5    59000      29400    5        1       0         0
6    Audi A5    52000      32000    5        1       0         0
7    Audi A5    72000      19300    6        1       0         0
8    Audi A5    91000      12000    8        1       0         0
9   Mercedez    67000      22000    6        0       0         1
10  Mercedez    83000      20000    7        0       0         1
11  Mercedez    79000      21000    7        0       0         1
12  Mercedez    59000      33000    5        0       0         1

In [6]:
final = merged.drop(['car_model', 'Audi A5'], axis='columns')
final

    Mileage  SellPrice  Age  BMW X5  Mercedez
0     69000      18000    6       1         0
1     35000      34000    3       1         0
2     57000      26100    5       1         0
3     22500      40000    2       1         0
4     46000      31500    4       1         0
5     59000      29400    5       0         0
6     52000      32000    5       0         0
7     72000      19300    6       0         0
8     91000      12000    8       0         0
9     67000      22000    6       0         1
10    83000      20000    7       0         1
11    79000      21000    7       0         1
12    59000      33000    5       0         1

In [7]:
reg_model = LinearRegression()

In [8]:
X = final.drop('SellPrice', axis='columns')
X

    Mileage  Age  BMW X5  Mercedez
0     69000    6       1         0
1     35000    3       1         0
2     57000    5       1         0
3     22500    2       1         0
4     46000    4       1         0
5     59000    5       0         0
6     52000    5       0         0
7     72000    6       0         0
8     91000    8       0         0
9     67000    6       0         1
10    83000    7       0         1
11    79000    7       0         1
12    59000    5       0         1

In [9]:
y = final.SellPrice
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: SellPrice, dtype: int64

In [10]:
reg_model.fit(X,y)

LinearRegression()

In [11]:
reg_model.predict([[69000, 6, 1, 0]])

array([18705.2723644])

In [12]:
reg_model.predict([[45000, 4, 0, 1]])

array([36991.31721061])

In [13]:
reg_model.predict([[86000, 7, 1, 0]])

array([11080.74313219])

In [14]:
reg_model.score(X, y)

0.9417050937281082

# One Hot Encoding Using SKlearn

In [15]:
df

   car_model  Mileage  SellPrice  Age
0     BMW X5    69000      18000    6
1     BMW X5    35000      34000    3
2     BMW X5    57000      26100    5
3     BMW X5    22500      40000    2
4     BMW X5    46000      31500    4
5    Audi A5    59000      29400    5
6    Audi A5    52000      32000    5
7    Audi A5    72000      19300    6
8    Audi A5    91000      12000    8
9   Mercedez    67000      22000    6
10  Mercedez    83000      20000    7
11  Mercedez    79000      21000    7
12  Mercedez    59000      33000    5

In [17]:
lb = LabelEncoder()
lbdf = df
lbdf.car_model = lb.fit_transform(lbdf.car_model)
lbdf

    car_model  Mileage  SellPrice  Age
0           1    69000      18000    6
1           1    35000      34000    3
2           1    57000      26100    5
3           1    22500      40000    2
4           1    46000      31500    4
5           0    59000      29400    5
6           0    52000      32000    5
7           0    72000      19300    6
8           0    91000      12000    8
9           2    67000      22000    6
10          2    83000      20000    7
11          2    79000      21000    7
12          2    59000      33000    5

In [36]:
x = lbdf[['car_model', 'Mileage', 'Age']].values
x

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]], dtype=int64)

In [37]:
y = lbdf.SellPrice
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: SellPrice, dtype: int64

In [38]:
ct = ColumnTransformer([('car_model', OneHotEncoder(), [0])], remainder='passthrough')

In [39]:
x = ct.fit_transform(x)
x

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [40]:
x[:, 1:]

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [45]:
model= LinearRegression()

In [46]:
model.fit(x, y)

LinearRegression()

In [48]:
model.predict([[0, 0, 1, 45000, 4]])

array([36991.31721061])

In [50]:
model.predict([[0, 1, 0, 86000, 7]])

array([11080.74313219])

In [51]:
model.score(x, y)

0.9417050937281083