In [39]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error

In [3]:
drug = pd.read_csv('../datasets/drugs.csv')

In [4]:
drug.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [7]:
drug.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [6]:
drug.duplicated().sum()

0

In [8]:
drug.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [10]:
sex = LabelEncoder()
drug['gneder'] = sex.fit_transform(drug['Sex'])

In [11]:
bp = LabelEncoder()
drug['bp'] = bp.fit_transform(drug['BP'])

In [12]:
cholesterol = LabelEncoder()
drug['cholesterol'] = cholesterol.fit_transform(drug['Cholesterol'])

In [13]:
drug.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug  gneder  bp  cholesterol
0   23   F    HIGH        HIGH   25.355  drugY       0   0            0
1   47   M     LOW        HIGH   13.093  drugC       1   1            0
2   47   M     LOW        HIGH   10.114  drugC       1   1            0
3   28   F  NORMAL        HIGH    7.798  drugX       0   2            0
4   61   F     LOW        HIGH   18.043  drugY       0   1            0

In [14]:
drug.tail()

     Age Sex      BP Cholesterol  Na_to_K   Drug  gneder  bp  cholesterol
195   56   F     LOW        HIGH   11.567  drugC       0   1            0
196   16   M     LOW        HIGH   12.006  drugC       1   1            0
197   52   M  NORMAL        HIGH    9.894  drugX       1   2            0
198   23   M  NORMAL      NORMAL   14.020  drugX       1   2            1
199   40   F     LOW      NORMAL   11.349  drugX       0   1            1

In [17]:
drug.drop(['Sex', 'BP', 'Cholesterol'], axis=1, inplace=True)

In [18]:
drug.head()

   Age  Na_to_K   Drug  gneder  bp  cholesterol
0   23   25.355  drugY       0   0            0
1   47   13.093  drugC       1   1            0
2   47   10.114  drugC       1   1            0
3   28    7.798  drugX       0   2            0
4   61   18.043  drugY       0   1            0

In [19]:
x = drug.drop('Drug', axis=1)
x.head()

   Age  Na_to_K  gneder  bp  cholesterol
0   23   25.355       0   0            0
1   47   13.093       1   1            0
2   47   10.114       1   1            0
3   28    7.798       0   2            0
4   61   18.043       0   1            0

In [29]:
y = drug['Drug']
y

0      drugY
1      drugC
2      drugC
3      drugX
4      drugY
       ...
195    drugC
196    drugC
197    drugX
198    drugX
199    drugX
Name: Drug, Length: 200, dtype: object

In [26]:
scaler = StandardScaler()
scaled = scaler.fit_transform(x)

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2)

In [32]:
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [41]:
y_pred = model.predict(x_test)

In [34]:
model.predict([[23,	25.355,	0,	0,	0]])

c:\Users\RAYANEH INS\miniconda3\envs\my_env\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['drugY'], dtype=object)

In [36]:
model.score(x_train, y_train)* 100

100.0

In [38]:
model.score(x_test, y_test)*100

97.5